name: project_june_client
description: 프로젝트 준 클라이언트.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.0
  flutter_native_splash: ^2.3.2
  flutter_phosphor_icons: ^0.0.1+6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0
  cached_query_flutter: ^1.0.0
  cached_storage: ^1.0.0
  dio: ^5.4.2+1
  json_annotation: ^4.8.1
  kakao_flutter_sdk_user: ^1.9.1+2
  kakao_flutter_sdk_share: ^1.9.1+2
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  lottie: ^2.6.0
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.1.14
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  firebase_analytics: ^10.10.0
  firebase_remote_config: ^4.4.0
  intl: ^0.18.1
  clock: ^1.1.1
  moment_dart: ^1.0.1
  flutter_app_badger: ^1.5.0
  sentry_flutter: ^7.10.1
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.6+7
  in_app_purchase_android: ^0.3.0+13
  in_app_purchase_platform_interface: ^1.3.5
  in_app_update: ^4.2.2
  new_version_plus: ^0.0.11
  appsflyer_sdk: ^6.12.2
  sprung: ^3.0.1
  word_break_text: ^0.1.0
  dotted_decoration: ^2.0.0
  extended_image: ^8.1.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  image: ^4.1.3
  package_info_plus: ^4.2.0
  share_plus: ^7.2.2
  in_app_review: ^2.0.8
  app_tracking_transparency: ^2.0.4
  animated_text_kit: ^4.2.2
  http: ^1.2.0
  async_button_builder: ^3.0.0+1
  mocktail: ^1.0.3
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  sentry_dart_plugin: ^1.6.0
  test: ^1.24.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/landing/
    - assets/images/sns/
    - assets/images/weather/
    - assets/images/navbar/
    - assets/images/home/
    - assets/lotties/
  fonts:
    - family: GowunDodum
      fonts:
        - asset: assets/fonts/GowunDodum-Regular.ttf
    - family: NanumJungHagSaeng
      fonts:
        - asset: assets/fonts/NanumJungHagSaeng.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
    - family: NanumDaCaeSaRang
      fonts:
        - asset: assets/fonts/NanumDaCaeSaRang.otf
    - family: NanumNoRyeogHaNeunDongHee
      fonts:
        - asset: assets/fonts/NanumNoRyeogHaNeunDongHee.otf
    - family: NanumDdarEGeEomMaGa
      fonts:
        - asset: assets/fonts/NanumDdarEGeEomMaGa.otf
    - family: NanumBbangGuNiMamSonGeurSsi
      fonts:
        - asset: assets/fonts/NanumBbangGuNiMamSonGeurSsi.otf
    - family: NanumMiRaeNaMu
      fonts:
        - asset: assets/fonts/NanumMiRaeNaMu.otf




sentry:
  project: 'sihyun-of-june-flutter'
  org: 'pygmalion-team'
  auth_token: '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'
