name: project_june_client
description: 프로젝트 준 클라이언트.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.1
  go_router: ^10.1.0
  page_transition: ^2.0.9
  flutter_native_splash: ^2.3.2
  flutter_phosphor_icons: ^0.0.1+6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/landing/
  fonts:
    - family: MaruBuri
      fonts:
        - asset: assets/fonts/MaruBuri-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/MaruBuri-Light.otf
          weight: 300
        - asset: assets/fonts/MaruBuri-Regular.otf
          weight: 400
        - asset: assets/fonts/MaruBuri-SemiBold.otf
          weight: 600
        - asset: assets/fonts/MaruBuri-Bold.otf
          weight: 700

